"""create pr_reviews table

Revision ID: 31a841f72f4f
Revises: c0fc08127288
Create Date: 2026-09-16 18:05:52.887219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a841f72f4f'
down_revision: Union[str, Sequence[str], None] = 'c0fc08127288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('pull_request_number', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('overall_assessment', sa.Text(), nullable=False),
    sa.Column('key_findings', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_reviews_pull_request_number'), 'pr_reviews', ['pull_request_number'], unique=False)
    op.create_index(op.f('ix_pr_reviews_repository_id'), 'pr_reviews', ['repository_id'], unique=False)
    op.create_index(op.f('ix_pr_reviews_user_id'), 'pr_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pr_reviews_user_id'), table_name='pr_reviews')
    op.drop_index(op.f('ix_pr_reviews_repository_id'), table_name='pr_reviews')
    op.drop_index(op.f('ix_pr_reviews_pull_request_number'), table_name='pr_reviews')
    op.drop_table('pr_reviews')
    # ### end Alembic commands ###
