"""make github_id unique per user

Revision ID: c0fc08127288
Revises: ccd5a668877f
Create Date: 2026-09-16 16:17:19.067937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fc08127288'
down_revision: Union[str, Sequence[str], None] = 'ccd5a668877f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('repositories_github_id_key'), 'repositories', type_='unique')
    op.create_unique_constraint('uq_repository_user_github', 'repositories', ['user_id', 'github_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_repository_user_github', 'repositories', type_='unique')
    op.create_unique_constraint(op.f('repositories_github_id_key'), 'repositories', ['github_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
