"""add authentication

Revision ID: ccd5a668877f
Revises: c21719808007
Create Date: 2026-09-13 03:21:27.105360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd5a668877f'
down_revision: Union[str, Sequence[str], None] = 'c21719808007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'repositories', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'user_id')
    # ### end Alembic commands ###
