"""GitHub Pull Request review comment service.

Generates structured Markdown review comments from diff-aware PR analysis and AI review,
and posts them directly to the GitHub PR timeline using authenticated credentials.

SAFETY:
Only posts comments to the GitHub PR timeline.
Does NOT modify repository contents, branches, commits, or database records.
"""

from __future__ import annotations

import json
import logging
import urllib.error
import urllib.request
from typing import Any

from app.core.config import settings
from app.models.repository import Repository
from app.services.ai_pr_reviewer import generate_ai_pr_review
from app.services.github import (
    GitHubAPIError,
    GitHubRateLimitError,
    GitHubRepoNotFoundError,
    GitHubServiceError,
)
from app.services.pr_reviewer import (
    PRNotFoundError,
    PRReviewResult,
    review_pull_request,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class PRCommenterError(Exception):
    """Base exception for PR commenter errors."""
    pass


class GitHubCredentialsUnavailableError(PRCommenterError):
    """Raised when GitHub token/credentials are missing or unauthorized."""
    pass


# ---------------------------------------------------------------------------
# Markdown comment builder
# ---------------------------------------------------------------------------

def format_pr_review_comment(
    summary: str,
    risk_level: str,
    overall_assessment: str,
    key_findings: list[dict],
    recommendations: list[str],
    include_findings: bool = True,
) -> str:
    """Construct a clean, professional GitHub Markdown comment from PR review data.

    Contains:
    - CodeLens header
    - Risk level
    - Overall assessment
    - Key findings (with severity, category, file path, line number, issue, impact, recommendation)
    - Prioritized recommendations
    """
    normalized_risk = risk_level.strip().lower()
    risk_emoji = {
        "critical": "🔴",
        "high": "🟠",
        "medium": "🟡",
        "low": "🟢",
    }.get(normalized_risk, "⚪")

    lines: list[str] = [
        "## 🔍 CodeLens AI PR Review",
        "",
        f"**Risk Level:** {risk_emoji} `{normalized_risk.upper()}`",
    ]

    if summary and summary.strip():
        lines.extend([
            "",
            f"> {summary.strip()}",
        ])

    if overall_assessment and overall_assessment.strip():
        lines.extend([
            "",
            "### 📋 Overall Assessment",
            overall_assessment.strip(),
        ])

    if include_findings:
        lines.extend([
            "",
            f"### 🚨 Key Findings ({len(key_findings)})",
        ])
        if not key_findings:
            lines.extend([
                "",
                "> ✅ **No critical issues detected.** CodeLens static analysis and AI review found no security, bug, or style defects in the changed lines of this PR.",
            ])
        else:
            for i, finding in enumerate(key_findings, 1):
                severity = str(finding.get("severity", "info")).upper()
                category = str(finding.get("category", "general")).capitalize()
                file_path = finding.get("file_path", "unknown")
                line_num = finding.get("line_number")
                loc = f"`{file_path}:{line_num}`" if line_num is not None else f"`{file_path}`"
                issue = finding.get("issue", "Issue detected.")
                impact = finding.get("impact", "")
                rec = finding.get("recommendation", "")

                lines.extend([
                    "",
                    f"#### {i}. [{severity}] {loc} — {category}",
                    f"- **Issue:** {issue}",
                ])
                if impact:
                    lines.append(f"- **Impact:** {impact}")
                if rec:
                    lines.append(f"- **Recommendation:** {rec}")

    if recommendations:
        lines.extend([
            "",
            "### 💡 Prioritized Recommendations",
        ])
        for i, rec in enumerate(recommendations, 1):
            lines.append(f"{i}. {rec}")

    lines.extend([
        "",
        "---",
        "*Review automatically generated by [CodeLens](https://github.com/yashvatsdev/codelens) — Diff-aware AI Code Review*",
    ])

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# GitHub REST API client for posting comments
# ---------------------------------------------------------------------------

def post_github_pr_comment(
    owner: str,
    repo: str,
    pr_number: int,
    body: str,
    token: str | None = None,
    timeout: int = 15,
) -> dict:
    """Post an issue/PR comment to GitHub using authenticated credentials.

    Endpoint: POST https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments

    Args:
        owner: Repository owner/organization.
        repo: Repository name.
        pr_number: Pull request number.
        body: Markdown content of the comment.
        token: Optional GitHub token override; defaults to settings.github_token.
        timeout: Request timeout in seconds.

    Returns:
        dict: Parsed GitHub API response containing `id`, `html_url`, etc.

    Raises:
        GitHubCredentialsUnavailableError: If token is missing or invalid.
        PRNotFoundError: If PR or repository is not found.
        GitHubRateLimitError: If rate limit is hit.
        GitHubAPIError: For other network or API errors.
    """
    auth_token = token or settings.github_token
    if not auth_token:
        raise GitHubCredentialsUnavailableError(
            "GitHub credentials are unavailable (missing GITHUB_TOKEN)"
        )

    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"
    payload = json.dumps({"body": body}).encode("utf-8")

    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "User-Agent": "CodeLens-App",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "Authorization": f"Bearer {auth_token}",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=timeout) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as err:
        if err.code == 404:
            raise PRNotFoundError(
                f"Pull request #{pr_number} not found: {url}"
            ) from err
        if err.code == 401:
            raise GitHubCredentialsUnavailableError(
                "GitHub authentication failed (invalid or expired GITHUB_TOKEN)"
            ) from err
        if err.code == 403:
            rate_remaining = err.headers.get("x-ratelimit-remaining")
            if rate_remaining == "0" or "rate limit" in str(err.reason).lower():
                raise GitHubRateLimitError(
                    "GitHub API rate limit exceeded. Please try again later."
                ) from err
            raise GitHubCredentialsUnavailableError(
                f"GitHub permission denied: {err.reason}"
            ) from err
        raise GitHubAPIError(
            f"GitHub API returned error {err.code}: {err.reason}"
        ) from err
    except urllib.error.URLError as err:
        raise GitHubAPIError(
            f"Failed to reach GitHub API: {err.reason}"
        ) from err
    except TimeoutError as err:
        raise GitHubAPIError(
            "Request to GitHub API timed out."
        ) from err


# ---------------------------------------------------------------------------
# Core coordination service
# ---------------------------------------------------------------------------

def create_pr_review_comment(
    repository: Repository,
    pull_request_number: int,
    summary: str | None = None,
    include_findings: bool = True,
    token: str | None = None,
    gemini_client: Any = None,
) -> dict:
    """Run diff-aware review, generate review summary, and post comment to GitHub PR.

    Args:
        repository: Repository model instance.
        pull_request_number: Pull request number.
        summary: Optional custom review summary.
        include_findings: Whether to include individual key findings.
        token: Optional GitHub token override.
        gemini_client: Optional mock Gemini client.

    Returns:
        dict with repository_id, pull_request_number, comment_id, comment_url, risk_level, findings_posted.
    """
    auth_token = token or settings.github_token
    if not auth_token:
        raise GitHubCredentialsUnavailableError(
            "GitHub credentials are unavailable (missing GITHUB_TOKEN)"
        )

    # 1. Run diff-aware PR review pipeline
    review_result = review_pull_request(
        owner=repository.owner,
        repo=repository.name,
        pr_number=pull_request_number,
        repository_id=repository.id,
    )

    # 2. Run AI PR review if Gemini is configured or mock client provided
    ai_review_succeeded = False
    if settings.gemini_api_key or gemini_client is not None:
        try:
            ai_review = generate_ai_pr_review(
                review_result=review_result,
                repo_full_name=repository.full_name,
                gemini_client=gemini_client,
            )
            risk_level = str(ai_review.get("risk_level", "low")).lower()
            review_summary = summary or ai_review.get("summary", "Code review completed.")
            overall_assessment = ai_review.get("overall_assessment", "")
            key_findings = ai_review.get("key_findings", [])
            recommendations = ai_review.get("recommendations", [])
            ai_review_succeeded = True
        except Exception as exc:
            logger.warning(
                "Gemini AI PR review generation failed, falling back to static analysis findings: %s",
                exc,
            )

    if not ai_review_succeeded:
        # Fallback review from static analysis findings
        findings_count = len(review_result.findings)
        has_errors = any(f.severity.lower() in ("error", "critical") for f in review_result.findings)
        risk_level = "low" if findings_count == 0 else ("high" if has_errors else "medium")
        if findings_count == 0:
            default_summary = f"CodeLens analyzed {review_result.files_analyzed} files in PR #{pull_request_number} with no issues detected."
        else:
            default_summary = f"CodeLens analyzed {review_result.files_analyzed} files in PR #{pull_request_number} and found {findings_count} potential issues."
        review_summary = summary or default_summary
        overall_assessment = "Diff-aware static code analysis completed for pull request changed lines."
        key_findings = [
            {
                "file_path": f.file_path,
                "line_number": f.line_number,
                "severity": f.severity,
                "category": f.category,
                "issue": f.message,
                "impact": f"Triggers static rule {f.rule_id}.",
                "recommendation": f"Remediate {f.rule_id} in {f.file_path}:{f.line_number or 1}.",
            }
            for f in review_result.findings
        ]
        recommendations = [
            "Review and resolve static analysis findings before merging."
        ] if findings_count > 0 else [
            "Code changes look clean and adhere to project standards."
        ]

    # 3. Format markdown comment
    comment_body = format_pr_review_comment(
        summary=review_summary,
        risk_level=risk_level,
        overall_assessment=overall_assessment,
        key_findings=key_findings,
        recommendations=recommendations,
        include_findings=include_findings,
    )

    # 4. Post comment to GitHub PR
    comment_data = post_github_pr_comment(
        owner=repository.owner,
        repo=repository.name,
        pr_number=pull_request_number,
        body=comment_body,
        token=auth_token,
    )

    findings_posted = len(key_findings) if include_findings else 0

    return {
        "repository_id": repository.id,
        "pull_request_number": pull_request_number,
        "comment_id": comment_data.get("id"),
        "comment_url": comment_data.get("html_url"),
        "risk_level": risk_level,
        "findings_posted": findings_posted,
    }
